server:
  port: 8090

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

jwt:
  token:
    secret: jwtsecret
    expired: 86400000